on:
  push:
    branches:
      - "beta"
    tags:
      - "v*.*.*"

name: CI
jobs:
  build_flatpak:
    name: "Build Flatpak"
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-48
      options: --privileged
    steps:
      - uses: actions/checkout@v4
      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: com.notepadqq.flatpak
          manifest-path: com.notepadqq.Notepadqq.yaml
          build-bundle: true
          upload-artifact: true
          branch: beta

  publish:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    needs: build_flatpak
    steps:
      - run: mkdir /tmp/artifacts

      - name: download artifact
        uses: actions/download-artifact@v4
        with:
          path: /tmp/artifacts

      - run: ls -R /tmp/artifacts

      - name: publish to github release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            /tmp/artifacts/com.notepadqq-x86_64.flatpak/com.notepadqq.flatpak
          tag_name: ${{ github.ref_name }}
          body: |
            notepadqq-flatpak
          draft: true
          generate_release_notes: true
          prerelease: contains(github.ref, 'pre')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
